quarkus.application.name=risk-service
quarkus.http.port=8081
quarkus.http.host=0.0.0.0

risk.latency.score-ms=2000
risk.latency.debts-ms=1500

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173,http://localhost:8080
quarkus.http.cors.methods=GET,OPTIONS
quarkus.http.cors.headers=accept,content-type

quarkus.smallrye-openapi.info-title=API de riesgos
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Servicio de consulta de score y deudas para la evaluacion de credito.
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
