quarkus.application.name=orchestrator-service
quarkus.http.port=8080
quarkus.http.host=0.0.0.0

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=austro
quarkus.datasource.password=austro_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/austro_credit
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=false

quarkus.rest-client.risk-service.url=${RISK_SERVICE_URL:http://localhost:8081}
quarkus.rest-client.risk-service.connect-timeout=3000
quarkus.rest-client.risk-service.read-timeout=6000

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=accept,content-type

quarkus.smallrye-openapi.info-title=API de evaluacion de creditos
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Servicio encargado de validar, evaluar y guardar solicitudes de credito.
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
